spring:
  datasource:
    url: ${ROUTIQO_DATABASE_URL}
    username: ${ROUTIQO_DATABASE_USER}
    password: ${ROUTIQO_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 8
      minimum-idle: 1
      connection-timeout: 5000
      validation-timeout: 2000
      connection-init-sql: SET statement_timeout = 5000
  flyway:
    enabled: true
    clean-disabled: true
    validate-on-migrate: true
