/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Owner-scoped keyset history. Cursor fields must be supplied together. No route endpoints or presence are returned. */
        get: operations["listBrowserJourneys"];
        put?: never;
        /** @description Retry with the same UUID and kind. Returns the original record even after completion; never restarts a completed journey. Owner comes only from the session. */
        post: operations["startBrowserJourney"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getBrowserJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{id}/complete": {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-only idempotent completion using server time; repeats return the original completion. */
        post: operations["completeBrowserJourney"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Same-origin bootstrap. Sets an HttpOnly CSRF cookie; send the returned masked token in X-XSRF-TOKEN for POST requests. Responses are no-store. */
        get: operations["getBrowserCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a five-minute challenge and sets its HttpOnly binding cookie. A newer challenge replaces the browser binding; no raw binding is returned. */
        post: operations["beginGoogleBrowserLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires the challenge binding cookie. Sets a 15-minute HttpOnly session cookie and clears binding. Session credentials never appear in the response body. No refresh token yet. */
        post: operations["exchangeGoogleBrowserLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBrowserSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Rotates a valid session in its last five minutes; otherwise returns its existing expiry. HttpOnly cookie only. Original Google authentication limits all replacements to 12 hours. Expired or revoked credentials cannot renew. A lost rotation response may require sign-in again. */
        post: operations["renewBrowserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/account/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Deletes this Routiqo account, its server journeys and all sessions. Requires Google authentication within five minutes; renewal does not reset that time. Local plans and the Google account remain unchanged. Reauthentication must be followed by explicit confirmation again. */
        post: operations["deleteBrowserAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Idempotently revokes the supplied session and clears session/binding cookies. CSRF is required even if already signed out. */
        post: operations["logoutBrowserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/native/auth/google/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a five-minute one-use challenge. Authorization, cookies, browser-origin headers and query strings are rejected. The binding remains only in native sign-in coordination memory. */
        post: operations["beginNativeGoogleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/native/auth/google/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verifies the one-use bound Google challenge and returns a 15-minute opaque native credential. Authorization, cookies, browser-origin headers and query strings are rejected. */
        post: operations["exchangeNativeGoogleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/native/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the enabled account for exactly one unexpired, unrevoked native bearer credential. Cookies, browser-origin headers and query strings are rejected. */
        get: operations["getNativeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/native/auth/session/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Returns the current session or atomically rotates it in its last five minutes. The Google-authenticated lineage remains bounded to 12 hours. */
        post: operations["renewNativeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/native/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Idempotently revokes the credential lineage. A retained rotated predecessor also revokes its active replacement; an unknown syntactically valid credential has no effect. */
        post: operations["logoutNativeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/native/auth/account/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Deletes the matching Routiqo account and all sessions. Requires Google authentication within five minutes; renewal does not reset that time. */
        post: operations["deleteNativeAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{id}/journal": {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Private journal for an owned completed trip; an unsaved annotation has version0. Commutes and active journeys are ineligible. */
        get: operations["getPrivateTripJournal"];
        put?: never;
        /** @description Save plain-text annotations with optimistic concurrency and latest-mutation replay protection. Twenty writes per account per minute. Empty title and notes clear the annotation content. */
        post: operations["savePrivateTripJournal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicit temporary lookup through the configured place provider. No persistence or presence. Twenty requests per account per minute. */
        post: operations["searchPrivateRoutePlaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Opt-in routing profile. Sends selected endpoints to the configured routing provider; does not start a journey or publish presence. Twenty requests per account per minute. Results are estimates; empty routes means no route found. */
        post: operations["calculatePrivateRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NativeEmptyRequest: Record<string, never>;
        NativeGoogleChallenge: {
            /** Format: uuid */
            id: string;
            nonce: string;
            binding: string;
            /** Format: date-time */
            expiresAt: string;
        };
        NativeExchangeRequest: {
            /** Format: uuid */
            challengeId: string;
            binding: string;
            idToken: string;
        };
        NativeSession: {
            /** Format: uuid */
            accountId: string;
            credential: string;
            /** Format: date-time */
            expiresAt: string;
        };
        NativeAccount: {
            /** Format: uuid */
            accountId: string;
        };
        NativeDeleteAccountRequest: {
            /** @enum {string} */
            confirmation: "DELETE";
            /**
             * Format: uuid
             * @description Must exactly match the authenticated native session account.
             */
            accountId: string;
        };
        TripJournal: {
            journey: components["schemas"]["Journey"];
            annotation: components["schemas"]["TripJournalAnnotation"];
        };
        TripJournalAnnotation: {
            /** @description Plain text; UTF-16 code-unit limit enforced by server */
            title: string;
            /** @description Plain text; UTF-16 code-unit limit enforced by server */
            notes: string;
            version: number;
            /** Format: date-time */
            updatedAt: string | null;
        };
        TripJournalWrite: {
            title: string;
            notes: string;
            /** @description Exact integer JSON number; no string coercion or fraction truncation. Numeric token at most 64 characters and absolute exponent at most 100. */
            expectedVersion: number;
            /** Format: uuid */
            mutationId: string;
        };
        /** @description Longitude then latitude. Longitude must be between -180 and180, latitude between -90 and90. Endpoints must differ. */
        RouteCoordinate: number[];
        RouteStep: {
            /** @description Trimmed plain text without control characters. */
            instruction: string;
            distanceMetres: number;
            durationSeconds: number;
            location: components["schemas"]["RouteCoordinate"];
        };
        Journey: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "trip" | "commute";
            /** @enum {string} */
            status: "active" | "completed";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        JourneyCursor: {
            /** Format: date-time */
            startedAt: string;
            /** Format: uuid */
            id: string;
        } | null;
        CsrfToken: {
            token: string;
        };
        GoogleChallenge: {
            /** Format: uuid */
            id: string;
            nonce: string;
            /** Format: date-time */
            expiresAt: string;
        };
        BrowserSession: {
            /** Format: uuid */
            accountId: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Destination: {
            id: string;
            name: string;
            region: string;
            /** @enum {string} */
            category: "Coast" | "Hills" | "Heritage";
            eyebrow: string;
            description: string;
            detail: string;
            highlights: string[];
            image: string;
            imageAlt: string;
            travelLabel: string;
            accent: string;
        };
    };
    responses: {
        /** @description Owned journey lifecycle record */
        JourneyResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Journey"];
            };
        };
        /** @description Missing, invalid, expired or revoked authentication; no credential details are returned. */
        AuthRejected: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Origin, fetch metadata or CSRF check failed. */
        AuthForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Body exceeds 20 KiB. */
        AuthTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description POST requires application/json. */
        AuthMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Request rate exceeded. */
        AuthLimited: {
            headers: {
                /** @description Retry delay in seconds. */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Missing, malformed, invalid, expired or revoked native bearer authentication, or prohibited Authorization on challenge/exchange. No credential details are returned. */
        NativeAuthRejected: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Cookie, Origin, Sec-Fetch-Site, query string, unknown native route or unsupported method was rejected. */
        NativeTransportRejected: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
        JourneyAccount: string;
        /** @description Must exactly match the configured browser origin. */
        AuthOrigin: string;
        /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
        AuthCsrf: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "UP";
                        /** @enum {string} */
                        service: "routiqo-core-api";
                    };
                };
            };
        };
    };
    listDestinations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Curated seed destinations, not live routing information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Destination"][];
                };
            };
        };
    };
    listBrowserJourneys: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Microsecond precision; pair with beforeId. */
                beforeStartedAt?: string;
                beforeId?: string;
            };
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded journey history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        journeys: components["schemas"]["Journey"][];
                        next: components["schemas"]["JourneyCursor"];
                    };
                };
            };
            /** @description Invalid page size or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            429: components["responses"]["AuthLimited"];
        };
    };
    startBrowserJourney: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    id: string;
                    /** @enum {string} */
                    kind: "trip" | "commute";
                };
            };
        };
        responses: {
            200: components["responses"]["JourneyResult"];
            /** @description Invalid identifier */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            /** @description Journey identity/kind conflict or another active journey */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    getBrowserJourney: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JourneyResult"];
            /** @description Invalid identifier */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            /** @description Journey absent or inaccessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["AuthLimited"];
        };
    };
    completeBrowserJourney: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            200: components["responses"]["JourneyResult"];
            /** @description Invalid identifier */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            /** @description Journey absent or inaccessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    getBrowserCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
            403: components["responses"]["AuthForbidden"];
            429: components["responses"]["AuthLimited"];
        };
    };
    beginGoogleBrowserLogin: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Pass nonce to Google sign-in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleChallenge"];
                };
            };
            403: components["responses"]["AuthForbidden"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    exchangeGoogleBrowserLogin: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    challengeId: string;
                    idToken: string;
                };
            };
        };
        responses: {
            /** @description Browser session established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSession"];
                };
            };
            /** @description Invalid JSON or request fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    getBrowserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled account for an unexpired, unrevoked browser session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        accountId: string;
                    };
                };
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            429: components["responses"]["AuthLimited"];
        };
    };
    renewBrowserSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Current or renewed browser session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSession"];
                };
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    deleteBrowserAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    confirmation: "DELETE";
                    /**
                     * Format: uuid
                     * @description Must match the session account shown when confirmation opened; rejects account switches in other tabs.
                     */
                    accountId: string;
                };
            };
        };
        responses: {
            /** @description Account deleted; session and binding cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Explicit confirmation required or invalid JSON */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            /** @description Sign in with Google again */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["AuthLimited"];
        };
    };
    logoutBrowserSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["AuthForbidden"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    beginNativeGoogleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeEmptyRequest"];
            };
        };
        responses: {
            /** @description Native Google challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeGoogleChallenge"];
                };
            };
            /** @description Body is not the exact empty JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NativeAuthRejected"];
            403: components["responses"]["NativeTransportRejected"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    exchangeNativeGoogleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeExchangeRequest"];
            };
        };
        responses: {
            /** @description Native session established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSession"];
                };
            };
            /** @description Invalid JSON */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NativeAuthRejected"];
            403: components["responses"]["NativeTransportRejected"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    getNativeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current native account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeAccount"];
                };
            };
            401: components["responses"]["NativeAuthRejected"];
            403: components["responses"]["NativeTransportRejected"];
            429: components["responses"]["AuthLimited"];
        };
    };
    renewNativeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeEmptyRequest"];
            };
        };
        responses: {
            /** @description Current or renewed native session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSession"];
                };
            };
            /** @description Body is not the exact empty JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NativeAuthRejected"];
            403: components["responses"]["NativeTransportRejected"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    logoutNativeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeEmptyRequest"];
            };
        };
        responses: {
            /** @description Credential lineage revoked or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body is not the exact empty JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NativeAuthRejected"];
            403: components["responses"]["NativeTransportRejected"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    deleteNativeAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeDeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Account deleted and all session lineages revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Explicit confirmation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NativeAuthRejected"];
            403: components["responses"]["NativeTransportRejected"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            /** @description Sign in with Google again */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["AuthLimited"];
        };
    };
    getPrivateTripJournal: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed trip and private annotation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripJournal"];
                };
            };
            401: components["responses"]["AuthRejected"];
            /** @description Journey missing or not owned by this account */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Journey is not a completed trip */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    savePrivateTripJournal: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripJournalWrite"];
            };
        };
        responses: {
            /** @description Saved completed-trip journal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripJournal"];
                };
            };
            /** @description Invalid annotation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            /** @description Journey missing or not owned by this account */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ineligible journey */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
        };
    };
    searchPrivateRoutePlaces: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Trimmed text; no semicolon or control characters; at most20 letter/number groups. */
                    query: string;
                };
            };
        };
        responses: {
            /** @description Temporary places and provider attribution; empty places means no matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        provider: "mapbox" | "photon";
                        attribution: string;
                        places: {
                            id: string;
                            label: string;
                            coordinate: components["schemas"]["RouteCoordinate"];
                        }[];
                    };
                };
            };
            /** @description Invalid search text */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            429: components["responses"]["AuthLimited"];
            /** @description Place provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    calculatePrivateRoute: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected verified account partition. Must equal the session account; never selects or authenticates an owner. Mismatch/missing returns401 to stop stale queued work after account switching. */
                "X-Routiqo-Account": components["parameters"]["JourneyAccount"];
                /** @description Must exactly match the configured browser origin. */
                Origin: components["parameters"]["AuthOrigin"];
                /** @description Masked token returned by GET csrf; browser must also send its CSRF cookie. */
                "X-XSRF-TOKEN": components["parameters"]["AuthCsrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    mode: "driving" | "walking" | "cycling";
                    origin: components["schemas"]["RouteCoordinate"];
                    destination: components["schemas"]["RouteCoordinate"];
                };
            };
        };
        responses: {
            /** @description Private route estimates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        provider: "mapbox" | "valhalla";
                        /** Format: date-time */
                        calculatedAt: string;
                        routes: {
                            distanceMetres: number;
                            durationSeconds: number;
                            geometry: components["schemas"]["RouteCoordinate"][];
                            /** @description Normalized English turn instructions. Optional only for compatibility with route responses produced before instructions were added. */
                            steps?: components["schemas"]["RouteStep"][];
                        }[];
                    };
                };
            };
            /** @description Invalid mode or endpoints */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            403: components["responses"]["AuthForbidden"];
            413: components["responses"]["AuthTooLarge"];
            415: components["responses"]["AuthMediaType"];
            /** @description Route endpoints or returned geometry exceed configured routing coverage. Empty body; no region or coordinate details are returned. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["AuthLimited"];
            /** @description Routing provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
